language: bash

services:
  - docker

env:
  - VERSION=1.6 VARIANT=php7.2
  - VERSION=1.6 VARIANT=php7.2/alpine
  - VERSION=1.6 VARIANT=php5.6
  - VERSION=1.6 VARIANT=php5.6/alpine

before_script:
  - env | sort
  - cd "$VERSION"
  - image="ud-klee/composer-with-prestissimo:${VERSION}${VARIANT:+-$VARIANT}"
  - image="${image//'/'/-}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - docker run "$image"

# vim:set et ts=2 sw=2:
